# Generated by Django 2.1 on 2019-08-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scholarship_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('income_level', models.IntegerField()),
                ('credit', models.FloatField()),
                ('grade', models.CharField(max_length=20)),
                ('taken_credit', models.IntegerField()),
                ('univ_name', models.CharField(max_length=20)),
                ('department_type', models.CharField(max_length=10)),
                ('disability', models.CharField(max_length=10)),
                ('national_merit', models.CharField(max_length=10)),
                ('apply_type', models.CharField(max_length=10)),
            ],
        ),
    ]
