# Generated by Django 2.1 on 2019-08-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship_info',
            name='apply_type',
        ),
        migrations.RemoveField(
            model_name='scholarship_info',
            name='department_type',
        ),
        migrations.RemoveField(
            model_name='scholarship_info',
            name='disability',
        ),
        migrations.RemoveField(
            model_name='scholarship_info',
            name='income_level',
        ),
        migrations.RemoveField(
            model_name='scholarship_info',
            name='national_merit',
        ),
        migrations.RemoveField(
            model_name='scholarship_info',
            name='taken_credit',
        ),
        migrations.RemoveField(
            model_name='scholarship_info',
            name='univ_name',
        ),
        migrations.AddField(
            model_name='scholarship_info',
            name='impaired',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='scholarship_info',
            name='income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarship_info',
            name='major',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='scholarship_info',
            name='merit',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='scholarship_info',
            name='regular_decision',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='scholarship_info',
            name='school',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='scholarship_info',
            name='year',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='scholarship_info',
            name='credit',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='scholarship_info',
            name='grade',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='scholarship_info',
            name='uid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
