# Generated by Django 2.1 on 2019-08-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('school', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('credit', models.CharField(blank=True, max_length=50, null=True)),
                ('income', models.IntegerField(blank=True, null=True)),
                ('impaired', models.CharField(blank=True, max_length=10, null=True)),
                ('merit', models.CharField(blank=True, max_length=10, null=True)),
                ('major', models.CharField(blank=True, max_length=50, null=True)),
                ('regular_decision', models.CharField(blank=True, max_length=10, null=True)),
                ('period', models.CharField(blank=True, max_length=50, null=True)),
                ('benefit', models.CharField(blank=True, max_length=50, null=True)),
                ('spec', models.CharField(blank=True, max_length=60, null=True)),
                ('stype', models.CharField(max_length=50)),
            ],
        ),
    ]
